// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace StudentDetailsManagement.Entity
{
    public partial class StudentDetails
    {
        public int StudentId { get; set; }
        public string FisrtName { get; set; }
        public string LastName { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public int Age { get; set; }
        public string FavoriteSubject { get; set; }
        public string InterestedCourse { get; set; }
        public int MathsMark { get; set; }
        public int ChemistryMark { get; set; }
        public int ComputerScienceMark { get; set; }
        public bool? IsDeleted { get; set; }
        public DateTime CreatedTimeStamp { get; set; }
        public DateTime UpdatedTimeStamp { get; set; }
    }
}